#ifndef MIN_HINT_HINT_H
#define MIN_HINT_HINT_H

typedef enum
{
	HINT_COLOUR_BLACK, HINT_COLOUR_RED, HINT_COLOUR_GREEN, HINT_COLOUR_YELLOW,
	HINT_COLOUR_BLUE, HINT_COLOUR_MAGENTA, HINT_COLOUR_CYAN, HINT_COLOUR_WHITE,

	HINT_COLOUR_BOLD_BLACK, HINT_COLOUR_BOLD_RED, HINT_COLOUR_BOLD_GREEN, HINT_COLOUR_BOLD_YELLOW,
	HINT_COLOUR_BOLD_BLUE, HINT_COLOUR_BOLD_MAGENTA, HINT_COLOUR_BOLD_CYAN, HINT_COLOUR_BOLD_WHITE,

	HINT_COLOUR_HIGHLIGHT_BLACK, HINT_COLOUR_HIGHLIGHT_RED, HINT_COLOUR_HIGHLIGHT_GREEN, HINT_COLOUR_HIGHLIGHT_YELLOW,
	HINT_COLOUR_HIGHLIGHT_BLUE, HINT_COLOUR_HIGHLIGHT_MAGENTA, HINT_COLOUR_HIGHLIGHT_CYAN, HINT_COLOUR_HIGHLIGHT_WHITE,

	HINT_COLOUR_RESET
} HintColourCode;

#define HINT_COLOUR_NORMAL_LENGTH				5
#define HINT_COLOUR_BOLD_LENGTH					7
#define HINT_COLOUR_HIGHLIGHT_LENGTH			9
#define HINT_COLOUR_RESET_LENGTH				4
#define HINT_COLOUR_MAX_LENGTH (HINT_COLOUR_RESET - 1)

char * hintColour(const char * text, HintColourCode code);

static void hintError(const char * message);

#endif
